### ISSUE TITLE
Artefatos UML + Documentação

### ISSUE THREAD

**Issue by diegomarinho** [jnortiz/Analisa-SuSy#11]
Podemos utiliza a ferramenta www.draw.io como suporte ao desenvolvimento

**Comment by diegomarinho** [comment]
Esta task tem origem da estória de número 1

**Comment by diegomarinho** [comment]
Diego: 2h - Criação e ajustes documento ESPECIFICAÇÃO FUNCIONAL.

https://drive.google.com/open?id=127RG_3V3LhelQOI-C7Nowesyoz6MBxLNTrVXqVbYF34

**Comment by evelynespinozat** [comment]
Descrição de RNF

**Comment by evelynespinozat** [comment]
Evelyn: 4h - Diagrama de comunicação, Diagrama de Sequência.

**Comment by lilianrc** [comment]
Lilian: 6h - Criação e alteração Diagrama de Componentes e Diagrama de Atividades.
