### ISSUE TITLE
Desenvolvimento + TDD

### ISSUE THREAD

**Issue by diegomarinho** [jnortiz/Analisa-SuSy#12]
Java + Junit = Arquitetura do Componente

**Comment by diegomarinho** [comment]
Esta task tem origem da estória de número 1

**Comment by marceloarj** [comment]
Marcelo C: 0,5 hora

**Comment by diegomarinho** [comment]
Diego: 1h test coverage + tdd

**Comment by diegomarinho** [comment]
Diego: 1h commit inicial dos fontes do componente
