### ISSUE TITLE
Manual Técnico na WIKI do Projeto

### ISSUE THREAD

**Issue by diegomarinho** [jnortiz/Analisa-SuSy#21]
Referente a estória 5

**Comment by diegomarinho** [comment]
Criar paginas e tópicos

https://github.com/jnortiz/Analisa-SuSy/wiki

**Comment by diegomarinho** [comment]
1 - Informar o que significa cada métrica. Exemplo:

As métricas a serem coletadas da ferramenta CCSM são definidas como segue. No escopo global:
 
FUNC_CNT: número de funções;
KW_CASE_CNT: número de aparições da palavra reservada CASE;
KW_BREAK_CNT: número de aparições da palavra reservada BREAK;
KW_GOTO_CNT: número de aparições da palavra reservada GOTO;
KW_CONTINUE_CNT: número de aparições da palavra reservada CONTINUE;
VAR_FILE_LOC_CNT: declarações de variáveis locais no escopo de arquivo. Um indicativo de variáveis globais.

**Comment by diegomarinho** [comment]
Gerar uma versao em PDF

**Comment by jnortiz** [comment]
Jheyne: 4 horas.

**Comment by diegomarinho** [comment]
Diego: 2h

**Comment by lilianrc** [comment]
Lilian: 10 h
