### ISSUE TITLE
Atualizar Especificação Funcional

### ISSUE THREAD

**Issue by diegomarinho** [jnortiz/Analisa-SuSy#22]
https://docs.google.com/document/d/127RG_3V3LhelQOI-C7Nowesyoz6MBxLNTrVXqVbYF34/edit#heading=h.hjntcbehd58a

**Comment by diegomarinho** [comment]
Referente a estória 5

**Comment by evelynespinozat** [comment]
Se atualizou  7 RF e 7 RNF

**Comment by evelynespinozat** [comment]
Se fiz diagramas e atualizou documento funcional. 10h
https://docs.google.com/document/d/14GChlL5tXO5J8NZynDyesCWp2jGRX77wVTsuVRjU-IU/edit#

**Comment by lilianrc** [comment]
Alteração Diagrama de Componentes e Diagrama de Atividades. Criação Diagrama de Estados. 6h
