### ISSUE TITLE
Atualizar o documento "Relatório Final - Grupo A"

### ISSUE THREAD

**Issue by diegomarinho** [jnortiz/Analisa-SuSy#30]

**Comment by diegomarinho** [comment]
https://docs.google.com/document/d/14GChlL5tXO5J8NZynDyesCWp2jGRX77wVTsuVRjU-IU/edit

**Comment by evelynespinozat** [comment]
6h - Acrescentei conteudo no Relatorio Final do seguinte:
- Equipe e papéis
- Monitoramento de riscos
- Diagramas de classe  com EASYUML
- Atualização de diagramas no relatorio final( Diagrama de estados, Diagrama de componentes, Diagrama de Actividades, Diagrama de comunicação,Diagrama de sequência, Arquitectura do projeto, Visão Lógica, Visão Fisica, Modelo de estado usado nos testes).

**Comment by diegomarinho** [comment]
Diego - 1h: Irei arrastar este card para DONE para gerar o gráfico de burndown da sprint 2.
