### ISSUE TITLE
Estudar as métricas existentes e Identificar ferramentas de mercado

### ISSUE THREAD

**Issue by diegomarinho** [jnortiz/Analisa-SuSy#9]
1 - Estudar as métricas
2 - Identificar ferramentas de mercado

**Comment by diegomarinho** [comment]
Esta task tem origem da estória de número 6

**Comment by diegomarinho** [comment]
diego: 1h

**Comment by jnortiz** [comment]
https://github.com/bright-tools/ccsm

**Comment by marceloarj** [comment]
Marcelo C: 2 horas
